=== cherifyounouss/projet_sgbd_dic1/xml/src/file.dtd
<!ELEMENT relations (relation+)>
<!ELEMENT relation (entite*,association)>
<!ELEMENT entite (nom+,attributs)>
<!ELEMENT attributs (matricule,nom,prenom)>
<!-- <!ELEMENT attributs (matiere,libelle)>
<!ELEMENT attributs (niveau,option,formation)> -->
<!ELEMENT association (nom+,attributs)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT matricule (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT matiere (#PCDATA)>
<!ELEMENT libelle (#PCDATA)>
<!ELEMENT niveau (#PCDATA)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT formation (#PCDATA)>
<!ATTLIST relation type PCDATA binaire>
<!-- <!ATTLIST relation type ternaire #IMPLED> -->

=== cherifyounouss/projet_sgbd_dic1/xml/src/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relations SYSTEM "file.dtd">
<relations>
    <relation type="binaire">
        <entite>
            <nom>Enseignant</nom>
            <attributs>
                <matricule type="String">M20014</matricule>
                <nom type="String">Mbacké</nom>
                <prenom type="String">Ahmadou Bamba</prenom>
            </attributs>
        </entite>
        <entite>
            <nom>Matière</nom>
            <attributs>
                <numMatiere type="String">20182009</numMatiere>
                <libelle type="String">SGBD</libelle>
                <!-- <attribut></attribut> -->
            </attributs>
        </entite>
        <association>
            <nom>Dispenser</nom>
            <attributs>
                <attribut></attribut>
            </attributs>
        </association>
    </relation>
    <relation type="ternaire">
        <entite>
            <nom>Enseignant</nom>
            <attributs>
                <matricule type="String">M20014</matricule>
                <nom type="String">Mbacké</nom>
                <prénom type="String">Ahmadou Bamba</prénom>
            </attributs>
        </entite>
        <entite>
            <nom>Classe</nom>
            <attributs>
                <niveau type="String">1</niveau>
                <option type="String">Informatique</option>
                <formation type="String">DIC</formation>
            </attributs>
        </entite>
        <entite>
            <nom>Matière</nom>
            <attributs>
                <numMatiere type="String">20182009</numMatiere>
                <libelle type="String">SGBD</libelle>
                <!-- <attribut></attribut> -->
            </attributs>
        </entite>
        <association>
            <nom>Faire cours</nom>
            <attributs>
                <attribut></attribut>
            </attributs>
        </association>
    </relation>

</relations>
