=== cherifyounouss/projet_sgbd_dic1/file.dtd
<!ELEMENT relations (relation+)>
<!ELEMENT relation (entite*,association)>
<!ELEMENT entite (nom,attributs)>
<!-- <!ELEMENT attributs (matricule,nom,prenom)>
<!ELEMENT attributs (matiere,libelle)> -->
<!ELEMENT attributs (matricule*,nom*,prenom*,niveau*,option*,formation*,matiere*,libelle*)> 
<!ELEMENT association (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT matricule (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT matiere (#PCDATA)>
<!ELEMENT numMatiere (#PCDATA)>
<!ELEMENT libelle (#PCDATA)>
<!ELEMENT niveau (#PCDATA)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT formation (#PCDATA)>
<!-- <!ATTLIST relation type CDATA "binaire">
<!ATTLIST matricule t CDATA #IMPLIED "String">
<!ATTLIST relation type ternaire #IMPLED> -->

=== cherifyounouss/projet_sgbd_dic1/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relations SYSTEM "file.dtd">
<relations>
    <relation>
        <entite>
            <nom>Enseignant</nom>
            <attributs>
                <matricule>M20014</matricule>
                <nom>Mbacké</nom>
                <prenom>Ahmadou Bamba</prenom>
            </attributs>
        </entite>
        <entite>
            <nom>Matière</nom>
            <attributs>
                <numMatiere>20182009</numMatiere>
                <libelle>SGBD</libelle>
                <!-- <attribut></attribut> -->
            </attributs>
        </entite>
        <association>
            <nom>Dispenser</nom>
            <attributs>
                <attribut></attribut>
            </attributs>
        </association>
    </relation>
    <relation>
        <entite>
            <nom>Enseignant</nom>
            <attributs>
                <matricule>M20014</matricule>
                <nom>Mbacké</nom>
                <prénom>Ahmadou Bamba</prénom>
            </attributs>
        </entite>
        <entite>
            <nom>Classe</nom>
            <attributs>
                <niveau>1</niveau>
                <option>Informatique</option>
                <formation>DIC</formation>
            </attributs>
        </entite>
        <entite>
            <nom>Matière</nom>
            <attributs>
                <numMatiere>20182009</numMatiere>
                <libelle>SGBD</libelle>
                <!-- <attribut></attribut> -->
            </attributs>
        </entite>
        <association>
            <nom>Faire cours</nom>
            <attributs>
                <attribut></attribut>
            </attributs>
        </association>
    </relation>
</relations>
